### PR TITLE
Fix memory corruption & slow parsing

### PR DESCRIPTION
**Pull request by csk-ableton**

### CODE REVIEW

**Comment by glynos** [comment]
LGTM.

**Comment by csk-ableton** [comment]
Great thanks for the quick merge!

**Comment by glynos** [comment]
For future reference, please use the official repo:

https://github.com/cpp-netlib/uri/

**Comment by csk-ableton** [comment]
That's the one I'm tracking. I must have picked the wrong one when forking, sorry.

**Pull request merged**
